# Acknowledgments {.unnumbered}

We gratefully acknowledge the efforts of hundreds of scientists and practitioners who have
contributed to the understanding of Myanmar’s terrestrial ecosystems over the past two centuries.
Our work is largely a synthesis exercise that would not have been possible without the dedication
and contributions of those before us.

We also acknowledge all contributors to this project, particularly those who attended workshops in
Myanmar over the last three years. Without input from a large and diverse expert group, the
development of the Myanmar Ecosystem Typology, the ecosystem descriptions and application of
the criteria would not have been possible. We also acknowledge the crucial support of field and GIS
staff at WCS Myanmar. Contributors to this assessment are listed within each ecosystem
assessment and in [Appendix 1](appendix_1.qmd).

The work to develop an IUCN Red List of Ecosystems of Myanmar was made possible through the
funding and support of Global Environment Facility Strengthening Sustainability of Protected Area
Management in Myanmar (GEF #5159, UNDP #5162) implemented by United Nations Development
Program and executed by the Myanmar Forestry Department and Wildlife Conservation Society.