# Summary {.unnumbered}

The Myanmar National Ecosystem Assessment contributes to the GEF funded Strengthening
Sustainability of Protected Area Management in Myanmar project. To support the Myanmar National
Ecosystem Assessment, Myanmar’s terrestrial ecosystems were assessed under the International
Union for the Conservation of Nature (IUCN) Red List of Ecosystems Categories and Criteria. This
report summarises the methods and findings of the assessment, including detailed ecological
descriptions of the 64 ecosystem types assessed.

A total of 64 ecosystem types were identified and evaluated under the IUCN Red List of
Ecosystems categories and criteria. Twenty-nine (45.3%) ecosystems were assigned a threatened
status, consisting of 8 (12.5%) Critically Endangered ecosystem types, 9 (14.1%) Endangered and
12 (18.8%) Vulnerable ecosystem types. One ecosystem type, Central Ayeyarwady Palm Savanna
ecosystem types was confirmed as Collapsed. A further two ecosystem types, Ayeyarwady kanazo
swamp forest and Southern Rakhine hills evergreen rainforest, were assessed with an upper
plausible status outcome of Collapsed, although their final assessment was Critically Endangered.

Twenty-eight ecosystem types were assessed as Near Threatened or Least Concern. However, a
post-assessment expert review by experts suggested that 11 of the 25 Least Concern ecosystems
could qualify for a different assessment outcome if more data was available. These 11 ecosystems
were reclassified to Data Deficient.

Thus, 17 of Myanmar’s ecosystem types were classified as Data Deficient. Data deficient
ecosystem types were primarily ecosystems for which there were historical records, but with
insufficient published information to assess the criteria (e.g. Rocky Tanintharyi karst). Alternatively,
there were insufficient distribution records to incorporate into our mapping workflow to allow
assessments of Criterion A and B (e.g. Grassy saltmarsh). Data deficient ecosystems also tended to
occur in regions that were inaccessible to field researchers due to travel restrictions (e.g. Shan
limestone grasslands). Urgent further work to confirm the distribution and assess the status of these
data deficient ecosystems is recommended.

This IUCN Red List of Ecosystems assessment has shown a dire situation for Myanmar’s
ecosystems. Of the area assessed, nearly two-thirds (64%, 426,628 km^2^) is mapped as a natural
ecosystem type, but of this over half (57.8%, 24,750 km^2^) of remaining area contains a threatened
ecosystem type (CR, EN or VU). This means over one third of Myanmar’s land area contains
threatened ecosystems. There needs to be an increase in conservation efforts to reverse this
situation and slow the trajectory towards collapse for ecosystems that are not currently threatened.
Conservation planning will be key to identify what are the best conservation actions and where to
apply them to reduce the risk of collapse for Myanmar’s natural ecosystems