## {{ params.ecosystem_name }} {.unnumbered}

```{python}
#| echo: false
# Parameters used in Python code blocks.
country_name = '{{ params.country_name }}'
ecosystem_names = {{ params.ecosystem_names }}
```

```{python}
#| echo: false
from IPython.display import Markdown, display

if ecosystem_names:
    ecosystem_name_str = ", ".join([f"{ecosystem_name['name']} [{ecosystem_name['reference']}]"
                for ecosystem_name in ecosystem_names])
else:
    ecosystem_name_str = 'No ecosystem names available.'
```

[Authors:]{.parameter .ecosystem-description-list} {{ ", ".join(params.authors) }}

[`{python} country_name` ecosystem names:]{.parameter .ecosystem-description-list} `{python} ecosystem_name_str`

[Global Classification:]{.parameter} {{ params.global_classification }}

[Functional Group:]{.parameter} {{ params.functional_group }}


[Global classification:]{.parameter} {{ params.global_classification }}

[IUCN Status:]{.parameter} **{{ params.iucn_status }}**


###### [Description]{.parameter}

{{ params.description }}

###### [Distribution]{.parameter}

{{ params.distribution }}

###### [Characteristic Native Biota]{.parameter}

{{ params.characteristic_native_biota }}

###### [Abiotic environment]{.parameter}

{{ params.abiotic_environment }}

###### [Key processes and interactions]{.parameter}

{{ params.key_processes_and_interactions }}

###### [Major threats]{.parameter}

{{ params.major_threats }}

###### [Ecosystem collapse definition]{.parameter}

{{ params.ecosystem_collapse_definition }}

###### [Assessment summary]{.parameter}

{{ params.assessment_summary }}**{{ params.assessment_outcome }}.**

###### [Assessment information]{.parameter}

TODO

###### [Assessment Outcome]{.parameter}

**{{ params.assessment_outcome }}.**

###### [Year Published]{.parameter}

{{ params.year_published }}

###### [Date Assessed]{.parameter}

{{ params.date_assessed }}

###### [Assessment Credits]{.parameter}

Assessed by: {{ params.assessed_by }}

Reviewed by: {{ params.reviewed_by }}

Contributions by: {{ params.contributions_by }}

###### [Criterion A]{.parameter}

{{ params.criterion_a_description }}

###### [Criterion B]{.parameter}

{{ params.criterion_b_description }}

###### [Criterion C]{.parameter}

{{ params.criterion_c_description }}

###### [Criterion D]{.parameter}

{{ params.criterion_d_description }}

###### [Criterion E]{.parameter}

{{ params.criterion_e_description }}